stages:
  - build
  - test
  - package
  - deploy

.maven-container:
  image: maven:latest
  tags:
    - maven
    - docker

myapp-build:
  stage: build
  extends: .maven-container
  before_script:
    - echo "Verifying maven installation..."
    - mvn --version
  script:
    - mvn compile

myapp-test:
  stage: test
  extends: .maven-container
  before_script:
    - echo "Running test cases..."
  script:
    - mvn test

myapp-package:
  stage: package
  extends: .maven-container
  script:
    - mvn package
  artifacts:
    paths:
      - target/

myapp-run:
  stage: deploy
  image: alpine/java:22
  tags: 
    - maven
    - docker
  script:
    - java -jar target/techapp-1.0.0.jar
