stages:
  - build
  - package

variables:
  DOCKER_IMAGE_NAME: "aar0njv/devops-practices"
  IMAGE_TAG: "maven_build-$CI_COMMIT_SHORT_SHA"

# Shell executor job for maven
myapp-build-test:
  stage: build
  tags:
    - devops
    - maven
    - shell
  before_script:
    - echo "Verifying maven installation..."
    - mvn --version
  script:
    - echo "Compiling and testing via shell executor..."
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week

docker-build-push:
  stage: package
  image: docker:24.0.5
  
  services:
    - name: docker:24.0.5-dind
      alias: docker
  
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  
  tags:
    - docker
    - maven
  
  dependencies:
    - myapp-build-test

  script:
    - echo "Building docker image locally..."
    - docker build --build-arg EXAMPLE_ARG=production -t maven_build:$CI_COMMIT_SHORT_SHA .
    
    # push to dockerhub
    - docker logout
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker tag maven_build:$CI_COMMIT_SHORT_SHA $DOCKER_IMAGE_NAME:$IMAGE_TAG
    - docker push $DOCKER_IMAGE_NAME:$IMAGE_TAG
    - docker logout

    # push to GL container registry
    - echo " Publishing to GL Container Registry... "
    - docker logout
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
    - docker tag maven_build:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE/maven-build:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE/maven-build:$CI_COMMIT_SHORT_SHA
    - docker logout
