stages:
  - build
  - test
  - package
  - deploy

default:
  tags:
    - maven
    - shell

myapp-build:
  stage: build
  image: maven:latest
  before_script:
    - echo "Verifying maven installation..."
    - mvn --version
  script:
    - mvn compile

myapp-test:
  stage: test
  image: maven:latest
  before_script:
    - echo "Running test cases..."
  script:
    - mvn test

myapp-package:
  stage: package
  image: maven:latest
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/
    expire_in: 1 week

docker-build:
  stage: package
  needs:
    - myapp-package

  script:
    - echo "Packaging..."
    - docker logout       # incase already logged in
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    - docker build -t maven_build:$CI_COMMIT_SHORT_SHA .
    - docker tag maven_build:$CI_COMMIT_SHORT_SHA aar0njv/devops-practices:maven-build-$CI_COMMIT_SHORT_SHA
    - docker push aar0njv/devops-practices:maven-build-$CI_COMMIT_SHORT_SHA
    - docker logout

    # Pushing to GL Container Registry
    - echo " Publishing to GL Container Registry... "
    - docker logout
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
    - docker tag maven_build:$CI_COMMIT_SHORT_SHA registry.gitlab.com/aar0njv-devops/maven-build:$CI_COMMIT_SHORT_SHA
    - docker push registry.gitlab.com/aar0njv-devops/maven-build:$CI_COMMIT_SHORT_SHA
